"""add_observability_columns

Revision ID: 4de456a8dc17
Revises: 006_add_image_url
Create Date: 2026-07-22 20:36:57.454426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de456a8dc17'
down_revision: Union[str, Sequence[str], None] = '006_add_image_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ai_thought', sa.String(length=500), nullable=True, comment='AI-generated thought for image overlay (20-35 words)'))
    op.add_column('posts', sa.Column('asset_urn', sa.String(length=255), nullable=True, comment='LinkedIn image asset URN (urn:li:image:...)'))
    op.add_column('posts', sa.Column('char_count', sa.BigInteger(), nullable=True, comment='Final content length in characters'))
    op.add_column('posts', sa.Column('category', sa.String(length=50), nullable=True, comment='Topic category (java_spring, python_async, etc.) for diversity analysis'))
    op.add_column('posts', sa.Column('llm_used', sa.String(length=50), nullable=True, comment='Which LLM model generated content (gemini-3.5-flash or ollama-gemma3:4b)'))
    op.add_column('posts', sa.Column('llm_fallback_used', sa.Boolean(), nullable=False, comment='Whether primary Gemini failed and fallback Ollama was used'))
    op.add_column('posts', sa.Column('tokens_used', sa.BigInteger(), nullable=True, comment='Estimated total tokens used for generation'))
    op.add_column('posts', sa.Column('execution_time_ms', sa.BigInteger(), nullable=True, comment='Total workflow execution time in milliseconds'))
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_index(op.f('ix_posts_llm_fallback_used'), 'posts', ['llm_fallback_used'], unique=False)
    op.create_index(op.f('ix_posts_llm_used'), 'posts', ['llm_used'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_llm_used'), table_name='posts')
    op.drop_index(op.f('ix_posts_llm_fallback_used'), table_name='posts')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_column('posts', 'execution_time_ms')
    op.drop_column('posts', 'tokens_used')
    op.drop_column('posts', 'llm_fallback_used')
    op.drop_column('posts', 'llm_used')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'char_count')
    op.drop_column('posts', 'asset_urn')
    op.drop_column('posts', 'ai_thought')
    # ### end Alembic commands ###
